<a href="https://colab.research.google.com/github/eric-stanley/tensorflow_developer/blob/master/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# import tensorflow
import tensorflow as tf
import numpy as np

print(tf.__version__)

2.15.0


0

In [ ]:
# create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
# create a vector
vector = tf.constant([10, 10])
vector
vector.ndim

1

In [ ]:
# create a matrix
matrix = tf.constant([[10, 7], [7, 10]])
matrix
matrix.ndim

2

In [ ]:
# create matrix with data type with dtype parameter
another_matrix = tf.constant([[10., 7.], [3., 2.], [8., 9.]], dtype=tf.float16)
another_matrix
another_matrix.ndim

2

In [ ]:
# create tensor
tensor = tf.constant([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])
tensor
tensor.ndim

3

In [ ]:
# create tensor with tf.Variable
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor
unchangeable_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [ ]:
# change element in changeable tensor
changeable_tensor[0] = 7
changeable_tensor[0]

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
# change using .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# change unchangable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [ ]:
# create random tensor
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

In [ ]:
# are the random tensors equal
random_1, random_2
print(random_1 == random_2)

tf.Tensor(
[[ True  True]
 [ True  True]
 [ True  True]], shape=(3, 2), dtype=bool)


In [ ]:
# shuffle the order of elements in tensor (valueable when you want to shuffle your data when inherent order doesn't effect learning)
not_shuffled = tf.constant([[10, 7], [3, 4], [2, 5]])
print(not_shuffled)
# set the global random seed
# tf.random.set_seed(42)
# set the operation random seed
print(tf.random.shuffle(not_shuffled, seed=42))

tf.Tensor(
[[10  7]
 [ 3  4]
 [ 2  5]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 3  4]
 [ 2  5]
 [10  7]], shape=(3, 2), dtype=int32)


In [ ]:
# other ways to create tensors
print(tf.ones([10, 7]))

tf.Tensor(
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]], shape=(10, 7), dtype=float32)


In [ ]:
# create tensors of all zeros
print(tf.zeros(shape=(3, 4)))

tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), dtype=float32)


In [ ]:
# convert numpy array into tensors
numpy_A = np.arange(1, 25, dtype=np.int32)
print(numpy_A)
# X = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) # non-capital for vector

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [ ]:
A = tf.constant(numpy_A, shape=(2, 3, 4))
B = tf.constant(numpy_A)
C = tf.constant(numpy_A, shape=(3, 8))
print(A)
print(B)
print(C)

tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4), dtype=int32)
tf.Tensor([ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24], shape=(24,), dtype=int32)
tf.Tensor(
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]], shape=(3, 8), dtype=int32)
